{"name": "Проверка авторизации курьера с неверным логином", "status": "failed", "statusDetails": {"message": "AssertionError: assert '{\"code\":404,\"message\":\"Учетная запись не найдена\"}' == {'message': 'Учетная запись не найдена'}\n +  where '{\"code\":404,\"message\":\"Учетная запись не найдена\"}' = <Response [404]>.text", "trace": "self = <test_login_courier.TestLoginCourier object at 0x102915640>\n\n    @allure.title(\"Проверка авторизации курьера с неверным логином\")\n    def test_login_courier_with_incorrect_login(self):\n        login_data = ScooterApiData.LOGIN_DATA\n        modified_data = modify_courier_data(login_data, 'login', 'user123')\n        response = requests.post(ScooterApiData.LOGIN_COURIER_POST_URL, modified_data)\n>       assert response.text == {\"message\":  \"Учетная запись не найдена\"}\nE       assert '{\"code\":404,\"message\":\"Учетная запись не найдена\"}' == {'message': 'Учетная запись не найдена'}\nE        +  where '{\"code\":404,\"message\":\"Учетная запись не найдена\"}' = <Response [404]>.text\n\ntests/test_login_courier.py:28: AssertionError"}, "start": 1725130349393, "stop": 1725130349641, "uuid": "0a9acf37-88ee-4a42-93a0-f0dc2020e994", "historyId": "38c994967c299b956c4bba6255559793", "testCaseId": "38c994967c299b956c4bba6255559793", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_incorrect_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "MacBook-Pro-Admin.local"}, {"name": "thread", "value": "4324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}